name: Run Python Email Script

on:
  schedule:
    - cron: '0 2,6,8 * * *' # 日本時間 24:05
  workflow_dispatch: # 手動実行用ボタン

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -q -U google-genai # 新しいSDKに変更

      - name: Run script
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python send_mail.py